# Key idea:
#
#   - clean is often used as a target that removes the output of other
#   targets, but it is not a special word in make.
#
# Reference:
#
#   https://makefiletutorial.com/#beginner-examples

some_file:
	touch some_file

clean:
	rm -f some_file
