# Key idea:
#
#   The default shell is /bin/sh. You can change this by changing the variable
#   SHELL.
#
# Reference:
#
#   https://makefiletutorial.com/#default-shell

SHELL=/bin/bash

cool:
	echo "Hello from ${SHELL}"
