# Key idea:
#
#   Illustrate how make knows it shouldn't rebuild a file if that file
#   exists and is up-to-date.
#
# References:
#
#   https://makefiletutorial.com/#beginner-examples

some_file:
	echo "This line will only print once"
	touch some_file
