# Key ideas:
#
#   * There's a nice list of options that can be run from make. Check out
#     --dry-run, --touch, --old-file.
#
#   * You can have multiple targets to make, i.e. make clean run test runs the
#     clean goal, then run, and then test.
#
# References:
#
#   https://makefiletutorial.com/#arguments-to-make
#   https://www.gnu.org/software/make/manual/make.html#Options-Summary
