# Key idea:
#
#   - The default target is the first target, so if there is only a single
#     target, the command(s) for that target will run.
#
# References:
#
#   https://makefiletutorial.com/#beginner-examples

some_file:
	echo "This line will always print."
