# Key idea:
#
#   - To list the possible targets, simply use tab completion and type:
#
#       make<space><tab><tab>
#
# References:
#
#   - https://github.com/scop/bash-completion
#
#   - [stackoverflow20101118] How do you get the list of targets in a makefile?
#     https://stackoverflow.com/questions/4219255/how-do-you-get-the-list-of-targets-in-a-makefile
#
#   - [stackoverflow20101115] bash completion of makefile target
#     https://stackoverflow.com/questions/4188324/bash-completion-of-makefile-target
